/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContactUsRouteImport } from './routes/contact-us'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as PanchakRouteImport } from './routes/panchak'
import { Route as Panchak2RouteImport } from './routes/panchak2'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as ProductsProductSlugRouteImport } from './routes/products/$productSlug'
import { Route as DashboardProductsIndexRouteImport } from './routes/dashboard/products/index'
import { Route as DashboardProductsCreateRouteImport } from './routes/dashboard/products/create'
import { Route as DashboardProductsProductSlugEditRouteImport } from './routes/dashboard/products/$productSlug.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactUsRoute = ContactUsRouteImport.update({
  id: '/contact-us',
  path: '/contact-us',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const PanchakRoute = PanchakRouteImport.update({
  id: '/panchak',
  path: '/panchak',
  getParentRoute: () => rootRouteImport,
} as any)
const Panchak2Route = Panchak2RouteImport.update({
  id: '/panchak2',
  path: '/panchak2',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const ProductsProductSlugRoute = ProductsProductSlugRouteImport.update({
  id: '/products/$productSlug',
  path: '/products/$productSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardProductsIndexRoute = DashboardProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardProductsCreateRoute = DashboardProductsCreateRouteImport.update({
  id: '/products/create',
  path: '/products/create',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardProductsProductSlugEditRoute =
  DashboardProductsProductSlugEditRouteImport.update({
    id: '/products/$productSlug/edit',
    path: '/products/$productSlug/edit',
    getParentRoute: () => DashboardRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/contact-us': typeof ContactUsRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/panchak': typeof PanchakRoute
  '/panchak2': typeof Panchak2Route
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/products/$productSlug': typeof ProductsProductSlugRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/products/create': typeof DashboardProductsCreateRoute
  '/dashboard/products/': typeof DashboardProductsIndexRoute
  '/dashboard/products/$productSlug/edit': typeof DashboardProductsProductSlugEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact-us': typeof ContactUsRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/panchak': typeof PanchakRoute
  '/panchak2': typeof Panchak2Route
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/products/$productSlug': typeof ProductsProductSlugRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/products/create': typeof DashboardProductsCreateRoute
  '/dashboard/products': typeof DashboardProductsIndexRoute
  '/dashboard/products/$productSlug/edit': typeof DashboardProductsProductSlugEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/contact-us': typeof ContactUsRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/panchak': typeof PanchakRoute
  '/panchak2': typeof Panchak2Route
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/products/$productSlug': typeof ProductsProductSlugRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/products/create': typeof DashboardProductsCreateRoute
  '/dashboard/products/': typeof DashboardProductsIndexRoute
  '/dashboard/products/$productSlug/edit': typeof DashboardProductsProductSlugEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/contact-us'
    | '/llms.txt'
    | '/panchak'
    | '/panchak2'
    | '/sitemap.xml'
    | '/products/$productSlug'
    | '/dashboard/'
    | '/dashboard/products/create'
    | '/dashboard/products/'
    | '/dashboard/products/$productSlug/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact-us'
    | '/llms.txt'
    | '/panchak'
    | '/panchak2'
    | '/sitemap.xml'
    | '/products/$productSlug'
    | '/dashboard'
    | '/dashboard/products/create'
    | '/dashboard/products'
    | '/dashboard/products/$productSlug/edit'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/contact-us'
    | '/llms.txt'
    | '/panchak'
    | '/panchak2'
    | '/sitemap.xml'
    | '/products/$productSlug'
    | '/dashboard/'
    | '/dashboard/products/create'
    | '/dashboard/products/'
    | '/dashboard/products/$productSlug/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  ContactUsRoute: typeof ContactUsRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  PanchakRoute: typeof PanchakRoute
  Panchak2Route: typeof Panchak2Route
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ProductsProductSlugRoute: typeof ProductsProductSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact-us': {
      id: '/contact-us'
      path: '/contact-us'
      fullPath: '/contact-us'
      preLoaderRoute: typeof ContactUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panchak': {
      id: '/panchak'
      path: '/panchak'
      fullPath: '/panchak'
      preLoaderRoute: typeof PanchakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panchak2': {
      id: '/panchak2'
      path: '/panchak2'
      fullPath: '/panchak2'
      preLoaderRoute: typeof Panchak2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/products/$productSlug': {
      id: '/products/$productSlug'
      path: '/products/$productSlug'
      fullPath: '/products/$productSlug'
      preLoaderRoute: typeof ProductsProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/products/': {
      id: '/dashboard/products/'
      path: '/products'
      fullPath: '/dashboard/products/'
      preLoaderRoute: typeof DashboardProductsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/products/create': {
      id: '/dashboard/products/create'
      path: '/products/create'
      fullPath: '/dashboard/products/create'
      preLoaderRoute: typeof DashboardProductsCreateRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/products/$productSlug/edit': {
      id: '/dashboard/products/$productSlug/edit'
      path: '/products/$productSlug/edit'
      fullPath: '/dashboard/products/$productSlug/edit'
      preLoaderRoute: typeof DashboardProductsProductSlugEditRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardProductsCreateRoute: typeof DashboardProductsCreateRoute
  DashboardProductsIndexRoute: typeof DashboardProductsIndexRoute
  DashboardProductsProductSlugEditRoute: typeof DashboardProductsProductSlugEditRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardProductsCreateRoute: DashboardProductsCreateRoute,
  DashboardProductsIndexRoute: DashboardProductsIndexRoute,
  DashboardProductsProductSlugEditRoute: DashboardProductsProductSlugEditRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  ContactUsRoute: ContactUsRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  PanchakRoute: PanchakRoute,
  Panchak2Route: Panchak2Route,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ProductsProductSlugRoute: ProductsProductSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
